name: Generate SBOM
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  generate_sbom_action:
    runs-on: ubuntu-latest
    name: Install bom and generate SBOM
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@8af7b2a5596dff526de9db59b2c4b8457e9f52a1 # v0.4.0
      - name: Generate SBOM
        run: |
          bom generate -o composable-resource-operator_${{github.ref_name}}_sbom.spdx \
          --dirs=.\
      - name: Upload SBOM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{github.ref_name}} composable-resource-operator_${{github.ref_name}}_sbom.spdx
